### ISSUE TITLE
SyntaxError when requiring RSchema gem

### ISSUE THREAD

**Issue by tjukes** [tomdalling/rschema#10]
Hey folks, I wanted to try out this gem but got stopped in my tracks: 
```
$ gem install rschema
Fetching: rschema-3.1.1.gem (100%)
Successfully installed rschema-3.1.1
Parsing documentation for rschema-3.1.1
Installing ri documentation for rschema-3.1.1
1 gem installed
$
$ irb
$ irb(main):001:0> require "rschema"
SyntaxError: /Library/Ruby/Gems/2.0.0/gems/rschema-3.1.1/lib/rschema/error.rb:5: syntax error, unexpected ','
    def initialize(schema:, value:, symbolic_name:, vars: {})
                           ^
/Library/Ruby/Gems/2.0.0/gems/rschema-3.1.1/lib/rschema/error.rb:28: syntax error, unexpected keyword_end, expecting end-of-input
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/rschema-3.1.1/lib/rschema.rb:4:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from (irb):1
	from /usr/bin/irb:12:in `<main>'
```
All apologies if this is my error, but I'd dearly love to know how to require it if `require "rschema"` doesn't work!

**Comment by tomdalling** [comment]
Hi Tana,

It's not you! The RSchema gem configuration says it works with Ruby 2.0 and above, but that has been incorrect for a while now. Unfortunately it is not compatible with the version of Ruby you're using (2.0).

You'll need a newer version of Ruby to use the gem. It is tested and working in Ruby 2.2, 2.3, and 2.4. I've updated the minimum required version in the gem configuration.

Thank you for reporting the problem, and sorry for the confusion.
